### ISSUE TITLE
What is the emitError option for?

### ISSUE THREAD

**Issue by ashishmondal** [adamfitzpatrick/tslint-stylish#6]
It looks like there is an option `emitError`, but I cannot find any documentation for it.

**Comment by adamfitzpatrick** [comment]
That option is actually associated with `gulp-tslint`. It breaks the pipeline on a linting error when set to true. It may be useful to include when I finally get around to properly updating this package.  For now, though, it is not part of this package. Thank you for mentioning it.

**Comment by VadimDez** [comment]
👍
