### ISSUE TITLE
maintained?

### ISSUE THREAD

**Issue by YouriT** [adamfitzpatrick/tslint-stylish#7]
Is this module still maintained?

Liked the approach but it doesn't work with latest versions of `gulp-tslint` sadly

**Comment by ghost** [comment]
Thanks for the heads-up.  This is a spare-time thing, so I'll get to it as soon as I can.

**Comment by YouriT** [comment]
Great!
As a side note, I've the feeling it isn't possible anymore the way you implemented it. A work around might be to use the `{format: 'json'}` option of `ts-lint` and pipe it to `tslint-stylish`

**Comment by adamfitzpatrick** [comment]
@YouriT Wanted to let you know that I'm finally getting on this.  I'll update everything to work with latest gulp-tslint, fix anything else that is out of date and generally clean it up.

**Comment by ghost** [comment]
@YouriT I have decided to close this ticket and cease maintenance of this package.  The folks over at Palantir have added a stylish formatter which provides output in essentially the same format as this one, and you can simply provide that as a string to the latest version of `gulp-stylish`:

```Javascript
gulp.task("tslint", () =>
        gulp.src("source.ts")
            .pipe(tslint({
                formatter: "stylish"
            }))
            .pipe(tslint.report())
    );
```

**Comment by YouriT** [comment]
Good to know, thanks!
